version: v{build}
image:
- Ubuntu
- Visual Studio 2015
configuration: Release
install:
- sh: sudo apt-get -y install uuid-dev libgles1-mesa mesa-utils-extra libgles2-mesa-dev mesa-utils freeglut3-dev mesa-common-dev
- git submodule update --init --recursive
before_build:
- cmd: powershell -command ". \"Tools/Build/Windows/build_windows.ps1\""
- sh: . "Tools/Build/Linux/build.sh"
build_script:
- cmd: msbuild Build/Windows/OrbitEngine.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- sh: make
after_build:
- cmd: appveyor PushArtifact Build/Windows/Release/OrbitEngine.lib
- sh: appveyor PushArtifact libOrbitEngine.a