version: v{build}
image:
- Ubuntu
- Visual Studio 2015
install:
- git submodule update --init --recursive
before_build:
- cmd: . "Tools/Build/Windows/build_windows.ps1"
- sh: . "Tools/Build/Linux/build.sh"
build: off
build_script:
- cmd: msbuild Build/Windows/OrbitEngine.sln
- sh: cd Build/Linux/ && make